/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gpu_GPUmm */

#ifndef _Included_gpu_GPUmm
#define _Included_gpu_GPUmm
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gpu_GPUmm
 * Method:    power
 * Signature: ([FI)V
 */
JNIEXPORT void JNICALL Java_gpu_GPUmm_power
  (JNIEnv *, jclass, jfloatArray, jint);

/*
 * Class:     gpu_GPUmm
 * Method:    power
 * Signature: ([JI)V
 */
JNIEXPORT void JNICALL Java_gpu_GPUmm_booleanPower
  (JNIEnv *, jclass, jobjectArray, jint);

#ifdef __cplusplus
}
#endif
#endif
